name: Swift

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode_11.2.app
        xcodebuild -version
        swift --version
    - name: Boot simulator
      run: xcrun simctl boot "iPhone 11 Pro"
    - name: Build for testing
      run: xcodebuild build-for-testing -workspace .swiftpm/xcode/package.xcworkspace -scheme Support-Package -destination "name=iPhone 11 Pro"
    - name: Run tests
      run: xcodebuild test-without-building -workspace .swiftpm/xcode/package.xcworkspace -scheme Support-Package -destination "name=iPhone 11 Pro"
